# Generated by Django 5.1.1 on 2024-12-30 17:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("client", "0001_initial"),
        ("store", "0002_product_stock_alter_product_category"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="category",
            field=models.CharField(
                choices=[("men", "Men"), ("women", "Women"), ("clothes", "clothes")],
                max_length=10,
            ),
        ),
        migrations.CreateModel(
            name="Checkout",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "payment_status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("PAID", "Paid"),
                            ("FAILED", "Failed"),
                        ],
                        default="PENDING",
                        max_length=20,
                    ),
                ),
                (
                    "payment_method",
                    models.CharField(
                        choices=[
                            ("INSTAPAY", "InstaPay"),
                            ("CASH", "Cash on Delivery"),
                        ],
                        default="CASH",
                        max_length=50,
                    ),
                ),
                ("shipping_address", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "order",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="checkout",
                        to="store.order",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        help_text="The user who placed the order",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="checkouts",
                        to="client.customer",
                    ),
                ),
            ],
        ),
    ]
