# Generated by Django 5.1.1 on 2025-01-02 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0009_rename_status_order_order_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="status",
            field=models.CharField(
                choices=[
                    ("PENDING", "Pending"),
                    ("PROCESSING", "Processing"),
                    ("SHIPPED", "Shipped"),
                    ("DELIVERED", "Delivered"),
                    ("CANCELLED", "Cancelled"),
                ],
                default="PENDING",
                max_length=20,
            ),
        ),
    ]
