# Generated by Django 5.1.1 on 2025-01-02 23:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0014_rename_order_status_order_orderstatus"),
    ]

    operations = [
        migrations.RenameField(
            model_name="order",
            old_name="orderstatus",
            new_name="orderstat",
        ),
    ]
