# Generated by Django 5.1.1 on 2025-01-02 23:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0015_rename_orderstatus_order_orderstat"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="order",
            name="orderstat",
        ),
    ]
