# Generated by Django 5.1.1 on 2025-01-02 23:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0016_remove_order_orderstat"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="orderstat",
            field=models.CharField(choices=[], default="PENDING", max_length=20),
        ),
    ]
