# Generated by Django 5.1.1 on 2025-01-02 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0018_alter_order_orderstat"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="status",
            field=models.CharField(choices=[], max_length=20),
        ),
    ]
